

# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sofia Game 
email: sofia.desousa@liip.ch
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username: 

# sass setings
sass:
  sass_dir: assets/styles/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
collections:
    games:
        output: true
        permalink: /:collection/:name

# <a href="http://127.0.0.1:4000/games/game2">
# ![alt text](https://ubistatic19-a.akamaihd.net/ubicomstatic/fr-fr/global/search-thumbnail/acm_ubi_thumb_leap_mobile_275895.jpg "Logo Title Text 1")
# </a>
# <a href="http://127.0.0.1:4000/games/game1" >
# ![alt text](http://www.50plusser.nl/forum/userpix/17401_mastermind_1.jpg "Logo Title Text 1")
# </a>
# ### Game 1
# <a href="http://127.0.0.1:4000/games/game1" >
# Mastermind
# </a>
# ### Game 2
# <a href="http://127.0.0.1:4000/games/game1" >
# Assassin's creed 
# </a>



# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
